### ISSUE TITLE
Checks are not re-run if mergeable.yml has changed

### ISSUE THREAD

**Issue by juandiana** [mergeability/mergeable#153]
Our use case is the following. We'd like to have our current milestone set in the mergeable.yml so that **only** PRs targeting the current milestone are able to be merged. Once we release this version, we'd like to change the milestone in mergeable.yml and have all PRs that were previously targeting this version re-run, so that the check passes as they now target the current milestone.

I believe this goes beyond this use case though. If you change your configuration on mergeable.yml, all PRs which mergeable reported something should re-run in order to reflect the up-to-date state with this new configuration.

**Comment by shine2lay** [comment]
@juandiana interesting, a few questions just to have a better understanding of your use case.

> Once we release this version, we'd like to change the milestone in mergeable.yml and have all PRs that were previously targeting this version re-run, so that the check passes as they now target the current milestone

you are referring to the PR that are still open after a release has been made?

> If you change your configuration on mergeable.yml, all PRs which mergeable reported something should re-run in order to reflect the up-to-date state with this new configuration

you are suggesting when the `mergeable.yml` in the base branch has changed, we should re-run all checks in PR that is opened against the base branch?

**Comment by juandiana** [comment]
Our work flow is pretty simple. One master branch and n feature branches. Each feature branch has a corresponding PR and resolves an issue. All PRs are required to target a certain milestone. Not every PR will make it into the next release (current milestone). Especially when we are near a release, there will be many PRs targeting the next milestone. Once we release, we want to change the milestone set in the mergeable.yml, so that all PRs that have the next milestone can be merged. If mergeable's bot doesn't pick up these changes, we would have to go to every PR and re-run the checks manually (which today involves editing some aspect of the PR like the description).

>you are referring to the PR that are still open after a release has been made?

Yeah

>you are suggesting when the mergeable.yml in the base branch has changed, we should re-run all checks in PR that is opened against the base branch?

Yes. Mergeable bot is configured via the `mergeable.yml` in the base branch right? In this case, it sounds reasonable that if that file has changed the PRs against that branch are refreshed to show the current status of the check.

**Comment by shine2lay** [comment]
@juandiana that makes sense. 

> Yes. Mergeable bot is configured via the mergeable.yml in the base branch right? 
Yes and No, if the PR include changes to `mergeable.yml` it'll read from the ref branch, else it'll read from the base branch.

> In this case, it sounds reasonable that if that file has changed the PRs against that branch are refreshed to show the current status of the check.
I agree

**Comment by jusx** [comment]
@juandiana I really like the idea of auto re-run of checks in PRs whenever `mergeable.yml` has changed in the default branch (i.e. master). Thank you for opening this issue! 

Just wanted your perspective. In your opinion, which is more useful to you and your team? #152 or this? We plan on implementing both but want to prioritize based on your feedback.

**Comment by jusx** [comment]
Sounds good @juandiana -- we will prioritize as such.

**Comment by shine2lay** [comment]
@jusx should this be a default? or should user specify some type of config? if so what would the config looks like?

**Comment by jusx** [comment]
@shine2lay IMHO -- this should be by default. I don't think we need to make it configurable right ATM.

I thinks it's very reasonable for checks to re-run when recipes are being updated in the HEAD branch. It makes the PR check status out-dated.

**Comment by shine2lay** [comment]
@jusx i did some research for this one, it seems we'll need to add 'content' permission for this to work. Should i implement this with a feature flag? or put this in the back of the queue?


![image](https://user-images.githubusercontent.com/5243508/77508736-9f627b00-6e28-11ea-8f9b-aaa7ae2a59b8.png)
