### ISSUE TITLE
Mergeable Server Error shows as Invalid Configuration

### ISSUE THREAD

**Issue by denis-sokolov** [mergeability/mergeable#167]
Here’s a failure I have encountered today. Notice how the summary says “Invalid configuration”, presumably the feature from #156, but the contents show a server error. The configuration has not been changed.

![image](https://user-images.githubusercontent.com/113721/52358932-8d195800-2a41-11e9-8c1e-eba6efbec22c.png)
![image](https://user-images.githubusercontent.com/113721/52358635-09f80200-2a41-11e9-98a4-d0580259bf20.png)

This is, of course, a minor cosmetic bug, the app is great!

**Comment by jusx** [comment]
Thank you for creating this issue! That's a really interesting message -- it looks like it's coming from the GitHub API when trying to retrieve the yml from the repo. 

Will look into better feedback :-)
