### ISSUE TITLE
Approve based on files changed

### ISSUE THREAD

**Issue by f2prateek** [mergeability/mergeable#184]
Hi! I'm not sure this workflow is supported, but we have a repo with two files, `staging.config` and `production.config` which provides the configuration we run in a given environment. Merging a change to `master` automatically triggers the deploy in appropriate environment. I'd like to automatically approve the PR if only the `staging.config` file  file has changed. If the `production.config`  has changed, I'd like to require at least two approvers. Is this possible?

**Comment by f2prateek** [comment]
A similar use case might be to automatically approve (or set different thresholds) for documentation updates vs code updates in a repo.

**Comment by jusx** [comment]
Hi @f2prateek 

This workflow is current not possible. However it would be simple to support by creating a `changeset` validator that verifies `includes` or `excludes` of modified files in a PR.

**Comment by jusx** [comment]
@f2prateek This is now possible via https://github.com/mergeability/mergeable#change-set
