### ISSUE TITLE
Validate description if certain files / paths have changed

### ISSUE THREAD

**Issue by digitalpardoe** [mergeability/mergeable#216]
In our workflow it would be valuable if we could validate the description against a regular expression if certain files in the repository have been changed.

For example if any file in the `module/migrations` directory changes we'd like to enforce a description outlining the change.

**Comment by shine2lay** [comment]
Hey @digitalpardoe ! Thanks for opening the issue.
Currently this is impossible but we have plans to add 'And' and 'Or' Logic into the validators level in the near future to open up the type of flow you mentioned.
