### ISSUE TITLE
Make size:ignore work with regex or globs

### ISSUE THREAD

**Issue by ohager** [mergeability/mergeable#217]
In a current project we use react snapshot testing...this may lead to huge changes and thus we need to "disable"  mergeable from time to time, because of rewritten snapshot files.
I figured out, that the the ignore setting in `size` works only with fixed filenames, and does not support filename patterns, e.g. globbing or regex.

Would be nice to have that feature!

**Comment by IllegalCactus** [comment]
@ohager This should be supported now as of: https://github.com/mergeability/mergeable/pull/218

If you’d like to give it a try 🙂

**Comment by shine2lay** [comment]
@ohager i believe @IllegalCactus 's PR has already implemented this feature!! :tada:  :tada: 
I'll go ahead and close this issue, please re-open if you found an issue
