### ISSUE TITLE
Stale PR comments only on work days feature?

### ISSUE THREAD

**Issue by Najki** [mergeability/mergeable#221]
The feature of commenting stale pull requests is nice but it not necessarily makes any good when these comments are posted on weekends when all developers are at home. They often ignore email notifications especially if they use their private GitHub accounts at work. And I can’t blame them. It’s their time off. 

Maybe it’s not the most important feature request but it would be nice to be able to set the days when stale PR comments are posted (or the days when they’re not supposed to be posted). 

I’m curious if other people would find it useful. Let me know by thumbs up or thumbs down reaction.

**Comment by shine2lay** [comment]
@Najki A few questions came into mind: how do we determine work days? does it includes holidays ? would timezone matter as well?

**Comment by Najki** [comment]
@shine2lay I was thinking about setting individual days (as an opt-in or opt-out per day of week). Anyway timezone seems to be a kill deal here. Having international development teams would make it impossible to configure efficiently. Too bad that Github doesn't have such feature in user settings then 😄
