### ISSUE TITLE
Make config file name / path configurable via `process.env`

### ISSUE THREAD

**Issue by al-the-x** [mergeability/mergeable#223]
The path and name of the config file is currently hard-coded to `.github/mergeable.yml`:

https://github.com/mergeability/mergeable/blob/b8d136c5095c411920eade8d12e571210c106aa5/lib/configuration/configuration.js#L143

In order to run a forked version of Mergeable alongside the mainstream GitHub app, we have to also alter the config file name in the fork, AFAICT. Would you be open to accepting a PR that makes that driven by an environment variable instead? Perhaps it defaults to the current value but can be overridden by an environment variable?

If so, I'd be happy to contribute... Thank you for your terrific work!

**Comment by shine2lay** [comment]
@al-the-x this make sense but i am having a hard time understanding the use case. If you run a version of Mergeable, you would already get all the functionality of mergeable already. I guess i am having a hard time understand the need to run 2 instance of mergeable side by side.

**Comment by al-the-x** [comment]
Thanks, @shine2lay,x and I'll try to explain my intent. I'd like to run the normal, configurable-by-repo Mergeable bot against a number of repos for my organization, but I'd also like to have a set of non-configurable checks set up in a central repo without having to copy and keep in sync the config files across repos. My assumption is that I could deploy my own Mergeable fork and point the config file to a different location where the shared config lives. I'd also like to contribute back to Mergeable and make some of the improvements that I know my team will need and want, like labeling Issues and PRs. In order to test those features, I presume that I will need to run Mergeable alongside my fork so that I can test and demonstrate the proposed changes in the fork with the reference implementation in `master`... Does any of that make sense?
