### ISSUE TITLE
Allow to split conditions different validators in separate checks

### ISSUE THREAD

**Issue by jack1142** [mergeability/mergeable#225]
One GitHub app can create multiple checks, so it would be nice if mergeable would support this (unless it does and I just don't know how set it up then I'll be thankful for any tips)

![image](https://user-images.githubusercontent.com/6032823/62891140-3c165380-bd45-11e9-8cd1-84682eaacea4.png)

**Comment by shine2lay** [comment]
@jack1142 Currently we can't do this yet and this is only because context between each `When: 'event'` is shared. When we add logic to run each `When` in it's own context, this will be available by doing something like this.

```
- When : 'pull_request.*'
    validate:
    pass: 
      do: checks
- When : 'pull_request.*'
    validate: 
    pass:
      do: checks # a different check 
```

**Comment by shine2lay** [comment]
I've been doing a bit of research on this, it seems we'll need to provide different 'name' in the checks in order to create separate checks, otherwise they get overwritten. what do you think about adding a `name` field for each when @jusx ?
