### ISSUE TITLE
Option to disable case insensitivity in regexes

### ISSUE THREAD

**Issue by jack1142** [mergeability/mergeable#226]
Currently mergeable generates regexes with `i` flag. It would be really nice if there was an option to make case sensitive regexes. For me, this is required in a project where I use AngularJS commit convention and the commit's type should be lower case.

**Comment by shine2lay** [comment]
@jack1142 good point. How do you imagine the config should look like?

**Comment by jack1142** [comment]
@shine2lay Hmm, either you could add option like `regex_case_sensitive` that would default to false and if it is true, mergeable would remove the `i` flag.

Or you could go one step further and allow setting other regex flags by adding `regex_flags` option (it would fault to `'i'` for backwards compatibility). Not sure if all flags (`g`, `i`, `m`, `s`, `u`, `y`) should be available to set since some don't really make sense to be used in mergeable (I would say `g` and `y` surely don't) but others might be worth supporting.

**Comment by shine2lay** [comment]
@jack1142 I like the 2nd option. For flexibility sake tho, i personally think allowing the users to specify any flag they want would be better than supporting a subset of the flags we choose . We could just try and catch the error if `regex` throws.

**Comment by jack1142** [comment]
@shine2lay About `g` flag, not supporting it would most likely just be a minor performance gain as it wouldn't waste resources on getting more matches, especially that for now mergeable doesn't output regex matches anywhere for user's use (unless it does and I just don't know about that 😄). However, if mergeable will support regex matches at some later date then this flag surely could be useful and so would `y` flag.

But yes, there's nothing wrong with allowing user to specify any flag, it's just that user won't really be able to get anything out of it without additional support in mergeable and implementing that obviously takes your time, so it just might be better to blacklist those 2 until you decide that you want to output regex matches for users to use to not give wrong impression. But that's for you to decide cause there's no bad implications when you don't blacklist them.
