### ISSUE TITLE
Milestone validator seems to fail, but github check passes

### ISSUE THREAD

**Issue by gschueler** [mergeability/mergeable#232]
Maybe my config is wrong, but i used a config similar to the example on the readme:

I want the pr to not be mergeable if no milestone is assigned:

```{.yaml}
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: milestone
        no_empty:
          enabled: true # Cannot be empty when true.
          message: 'Milestone must be assigned before merging.'
```

The pr has no milestone, the check shows as a big red X, but it says all validators returned 'pass':

![Screen Shot 2019-10-03 at 2 53 17 PM](https://user-images.githubusercontent.com/55603/66166958-97e6b580-e5ed-11e9-87f2-1ccb42bbcfc2.png)

**Comment by shine2lay** [comment]
@gschueler that's very interesting, the Details section shouldn't even showed if the mergeable status is "pass" do you have a link you can share? I'll try to debug it a bit later

**Comment by gschueler** [comment]
there are a number of prs in our repo like this now https://github.com/rundeck/rundeck/pull/5333/checks

**Comment by shine2lay** [comment]
It seems this is no longer an issue please re open if it still persist
