### ISSUE TITLE
Review required from members of a Team

### ISSUE THREAD

**Issue by JonasHornung** [mergeability/mergeable#236]
Hi,
we have the following situation:
We got two teams with write access to our repository and we'd like to have reviews/approvals of 2 members of the first team and 1 member of the second team to approve a pull-request to be mergeable. We tried some different approaches with mergeable: Insert the Team-Names as reviewers, Insert the team names in the CodeOwners file, but both didn't work (in the second scearnio mergeable didn't finish at all, it was running for almost half an hour).
Do you have any idea how our requirement could be solved using mergeable? Or do you maybe plan to implement to support team-names as required reviewers?

Thanks you very much!

**Comment by shine2lay** [comment]
hey @JonasHornung! that is a cool feature request, currently mergeable doesn't know the concept of team member vs regular users. From a quick glance at github api, this is something that can be implemented in mergeable but unfortunately i'll be busy for next month or so. I can try to get to this after that. If you wish to write the feature and submit a PR, i'll do my best to review and get it deployed ASAP.
