### ISSUE TITLE
[NEW Validators] check git commit message

### ISSUE THREAD

**Issue by zhongjiajie** [mergeability/mergeable#241]
In Apache-Airflow dev workflow, we find out only check Github PR title or PR describe is not enough, sometime we should check git commit message to make git history consistency. Otherwise, the git history will look like below
![](https://tva1.sinaimg.cn/large/006tNbRwgy1gav66czxwyj311m0gkwis.jpg)
ref: https://github.com/apache/airflow/pull/7144#issuecomment-573490229

**Comment by shine2lay** [comment]
@zhongjiajie one quick question: 
- check against all the commit messages, just a subset or at least one needs to follow the pattern?

**Comment by zhongjiajie** [comment]
@shine2lay Hi, Airflow community have a discuss in https://github.com/kaxil/boring-cyborg/pull/2#discussion_r365774746 , these two situation which dependent on PR is single commit or multiple, if single commit we should check the only one commit, but if multiple commit we should check the first one/PR title cause we could squashed the commit by committer

**Comment by shine2lay** [comment]
@zhongjiajie 
``` 
but if multiple commit we should check the first one
```
just wanted to double check, the first one meaning the oldest commit? or the latest commit?

**Comment by zhongjiajie** [comment]
@shine2lay  Oldest, cause second, third or add more commit maybe just `Fix ci` or `Change as suggest` or something meaningless

**Comment by rfgamaral** [comment]
I want to give my support to this feature to work similar to [semantic-pull-requests](https://github.com/zeke/semantic-pull-requests).

I personally need additional checks that `mergeable` gives me but `semantic-pull-requests` doesn't. Instead of using two status checks, I'd like to use one, **`mergeable`**. Only thing I'm missing for now is the ability to check for conventional commit messages for all commits in the PR branch.

**Comment by shine2lay** [comment]
@rfgamaral I am WIP on this, should be expected to be done within a couple of days. 
Just to double check, you want all the commit to follow a certain regex?

**Comment by rfgamaral** [comment]
> @rfgamaral I am WIP on this, should be expected to be done within a couple of days. 
> Just to double check, you want all the commit to follow a certain regex?
> 

Yes. Looking at this repository configuration you have regex for the PR title to follow conventional commits, I'm looking at the same exact configuration for both the PR title and all PR commits.

It would be great if there was some way to configure that without duplicating the validation regex for both the PR title and commits though.

**Comment by zhongjiajie** [comment]
Looking forward about the new feature.

**Comment by shine2lay** [comment]
@zhongjiajie @rfgamaral This feature has been merged and deployed. Try it out and please let us if the implementation doesn't satisfy your use case or there is a bug.

**Comment by rfgamaral** [comment]
@shine2lay I haven't tested it yet per se, but I'm now using it in a couple of repositories, like this one:

- https://github.com/rfgamaral/eslint-config-typescript-unified/blob/master/.github/mergeable.yml

It would've been nice if we could avoid that title and commit message duplication...

**Comment by shine2lay** [comment]
hey @rfgamaral - I think we can potentially add a way to capture sub options that can be reused by any validators or actions to solve the message duplication but it is non-trivial to implement. This is something we might implement in the future. I'll create an issue to track this feature. 

The other possible solution is to build a edge case specifically around `title and commit` which has a very limited use case and i don't think it's worth it to implement.
