### ISSUE TITLE
Ability to share a config across multiple repos

### ISSUE THREAD

**Issue by IllegalCactus** [mergeability/mergeable#244]
Hi,

We use Mergeable across a large number of repositories in my organisation. I was wondering if there's a way we could make this workflow a bit simpler by having a 'default' config file across many repos.

The idea I had was: have a convention where you can specify a default `mergeable.yml` either:

- Inside a `.github` repository in your organisation, which is already used to specify org-wide code of conduct and pull request templates: https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file
- Inside a `.mergeable` repository (same as above, but specific to Mergeable)

Mergeable would then use the following priority to decide which file to use

1. A `mergeable.yml` that is added/updated by the PR.
2. Else, a `mergeable.yml` inside the current repo.
3. Else, a `mergeable.yml` inside the 'default' repo.

The use case, as I see it, would be:

- Being able to add Mergeable to a new repo more easily (one click vs. needing to add a file).
- Only have to update config in one place if it's shared across multiple repos (all of our repos use the same config).
- Still able to override the default if need be.

The choice of config file would be all-or-nothing (no merging of files) to keep things simple.

Let me know what you think about this. Is that a feature you would be interested in? I'd be happy to help with a PR if so 🙂 .

**Comment by shine2lay** [comment]
@IllegalCactus I like this a lot. I have a couple of question:
1. How is the 'default' repo determined? I am not familiar with this feature in github and wasn't able to do a quick search to find out.
2. What do you think about a case where i have `mergeable.yml` in the 'default' repo but they don't necessarily want to use it for all repo?

**Comment by IllegalCactus** [comment]
@shine2lay 

1. It's not super well documented. The only mention of this I can find is on the page I linked above ^. GitHub will use contributing guidelines and PR templates from a repo called `.github` as a default for your org, so you don't have to put one in every repo. This doesn't seem to be configurable - it will only ever look in a repo called `.github` by convention. My idea was to just piggyback on this convention. It's nice because it mirrors the path Mergeable currently uses in the repo (`.github/mergeable.yml`). Alternatively, Mergeable could have a convention of looking for a `.mergeable` repo instead.

2. What I had in mind was, you would override the default by including a `mergeable.yml` in your repo. The default would only be used if Mergeable couldn't find one in the specific repo. Is that what you meant?

**Comment by shine2lay** [comment]
@IllegalCactus 
1. This feature sounds great! I think we should still keep `.github/mergeable.yml` path just to avoid confusion.
2. I understood that, what i meant was (and this is probably extreme edge case) that if i have `mergeable.yml` in `default` repo, how do we turn it off in certain repos? Maybe there is one repo where user doesn't want mergeable to run at all.

**Comment by IllegalCactus** [comment]
> if i have mergeable.yml in default repo, how do we turn it off in certain repos? Maybe there is one repo where user doesn't want mergeable to run at all.

Ah, I see what you mean. Could this not be achieved by just uninstalling Mergeable from that repo / installing it on specific ones? I.e. this option:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/2632211/73385429-0d754080-42c5-11ea-954e-7b0d3d00e3cd.png">

Might not be super convenient if you have lots of repos I suppose, but still doable.

**Comment by shine2lay** [comment]
@IllegalCactus -
oh yeah, this will work. I completely forgot about this solution. I think this is a great idea!!

**Comment by jusx** [comment]
@IllegalCactus I too would prefer to go with `.github` -- probot supports a lot of what you describe out of the box through `context.config`

Take a at https://github.com/probot/probot/blob/1a19bdd/src/context.ts 

There's also support for merging. It may very well support what you are wanting to achieve.

I'd be happy to approve the PR should you open one.

**Comment by IllegalCactus** [comment]
Thanks for the link @jusx - seems like that will save a bit of work.

It looks like `context.js` uses `deep-merge` for its merging. I played around with that library a while ago, and couldn't get it working nicely with Mergeable unfortunately. `deep-merge` concatenates lists, so because of how `mergeable.yml` is structured it ends up appending the contents of the two files together and not overwriting things when you'd want it to.  So it'll produce duplicate validators for instance.

**Comment by shine2lay** [comment]
closed by #291
