### ISSUE TITLE
How to ignore coding comments from max count ?

### ISSUE THREAD

**Issue by krazykira** [mergeability/mergeable#245]
`version: 2
mergeable:
  - when: pull_request.opened, pull_request.edited, pull_request.synchronize
    validate:
      - do: size
        ignore: ["**/*.json",  "**/*.md","**/*.xml"]
        lines:
          max:
            count: 500
            message: The change is very big for reviewing. Try splitting the PR into multiple self-contained changes.`

In the above config how can i add a condition so that all the comments in my code are excluded from counting when mergeable calculates the max count. e,g: comments like below should be ignored when counting.

```
/**
* Want to ignore this from the max count 500 so that mergeable doesn't fail my PR
*/

/*
* Also comments like these should be ignored from max count
*/
```

**Comment by shine2lay** [comment]
@krazykira This is currently not possible in mergeable because we aren't reading the files directly, we just query github to see which files have changed and how many lines have been changed in each file.

**Comment by krazykira** [comment]
@shine2lay So is there any plan to implement this functionality in the future ?

**Comment by shine2lay** [comment]
@krazykira while i can see a solution to this problem, it'll require read permission of the code which we currently don't require and it won't be a trivial implementation. I doubt we'll implement this in the near future. 
that being said, if you would like to implement and create a PR, I'll be happy to help you.
