### ISSUE TITLE
Installing the app on a repo should not automatically enforce new checks when a config file is not present

### ISSUE THREAD

**Issue by mbestavros** [mergeability/mergeable#252]
I installed Mergeable to a repo on Friday, with the intention of fleshing out some rules this week.

However, a team member submitted an unrelated PR over the weekend that happened to not include a description. Seemingly out of the blue, Mergeable fails and prevents it from being merged. With a little digging, I found that Mergeable loads an [undocumented series of default checks](https://github.com/mergeability/mergeable/pull/205) when no configuration file is present, including one that fails if no description is present.

IMO, this is not a good out-of-box experience. When installing Mergeable, I did not expect, nor was I notified, that I would also be enrolled in a set of tests I had no input on. These default tests are not documented anywhere on the repo's README, either, so I had no way to know they would run.

The default when no config file is present should be to not run anything. If I wish to make use of Mergeable, I will add a config file, with my own rules. Until that happens, Mergeable should not change my repo's behavior.

**Comment by jusx** [comment]
@mbestavros Hi -- thank you for bringing this up. We agree with you, and will be working on removing these defaults.
