### ISSUE TITLE
Error when registering Validators and actions

### ISSUE THREAD

**Issue by shine2lay** [mergeability/mergeable#258]
### Context
Found the following error (multiple times in the log), not sure of the root causes yet, creating an issue to make sure we are aware and be able to tackle it.
![image](https://user-images.githubusercontent.com/5243508/77016819-074f2800-6936-11ea-95f9-51f4a431abca.png)

**Comment by kevnm67** [comment]
@shine2lay Would this have anything to do with the error below?  I just starting seeing this error.

```
Invalid Validators or Actions

Error: Validators have thrown Error: Cannot find module './validators/checks,'
Require stack:

/app/lib/register.js
/app/lib/flex.js
/app/lib/mergeable.js
/app/index.js
/app/node_modules/probot/lib/resolver.js
/app/node_modules/probot/lib/index.js
/app/node_modules/probot/bin/probot-run.js

```

**Comment by shine2lay** [comment]
@kevnm67 we just released a few error handling code recently, it just started to surface error that has been in the logs but never shown to the shown to the users. The behaviour you see is intended.
You are getting that error because 'checks' is an `action`, not a `validator` so our codebase couldn't find proper code to execute.

**Comment by kevnm67** [comment]
@shine2lay Thanks for the explanation.  I'll update our configs!
If it makes sense, I think it would be helpful to include a human readable/facing error message.  Thoughts?

**Comment by shine2lay** [comment]
@kevnm67 yes, i agree 100%. What type of message do you think will be helpful to you? I thought saying "Invalid validator or actions" would be enough but i guess i was wrong

**Comment by shine2lay** [comment]
unable to reproduce, closing

**Comment by kevnm67** [comment]
@shine2lay Sorry for the delay.  Something related to your above comment regarding `checks` being an action, not a `validator`.
