### ISSUE TITLE
TypeError: glob pattern string required

### ISSUE THREAD

**Issue by pkuczynski** [mergeability/mergeable#285]
❗ Validator: INTERNAL ERROR

Status ERROR

❗ Internal error!
Input :
Settings : {}
Error : This is a mergeable bug, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new

```
TypeError: glob pattern string required
    at minimatch (/app/node_modules/minimatch/minimatch.js:94:11)
    at /app/lib/validators/dependent.js:48:57
    at Array.some (<anonymous>)
    at Dependent.validate (/app/lib/validators/dependent.js:48:38)
    at async Promise.all (index 5)
    at async processWorkflow (/app/lib/flex.js:127:22)
    at async executeMergeable (/app/lib/flex.js:37:3)
    at async /app/lib/mergeable.js:87:7
```

This is my config:
https://github.com/rvm/rvm/blob/master/.github/mergeable.yml

**Comment by shine2lay** [comment]
@pkuczynski I am looking into it now

**Comment by pkuczynski** [comment]
Thanks!

**Comment by shine2lay** [comment]
hey @pkuczynski i see that in your third `do: dependent` , there is no `file` option. That was causing the error.
![image](https://user-images.githubusercontent.com/5243508/79279728-85361e80-7e63-11ea-9cbb-b5ecf3fc4b17.png)

if you meant to mean all files are dependent upon one another, you should remove the `changed` option. 
see https://github.com/mergeability/mergeable#dependent . 

I'll also fix it to make the error more human friendly

**Comment by pkuczynski** [comment]
Seems that it works [now](https://github.com/rvm/rvm/pull/4912), thanks for the advice :)
