### ISSUE TITLE
Dependent validator seems to be limited to 30 files

### ISSUE THREAD

**Issue by alexbegg** [mergeability/mergeable#350]
I am having a dependent validator that is failing on a PR that has 81 python files.

The validator is set to
```
- do: dependent
  changed:
    file: 'dags/**/*.py'
    files: ['helm/values.yaml']
  message: 'A dags file changed, you must push up the new image and then paste the image digest into the helm/values.yaml file.'
```

The PR in question for has 79 files matching `dags/**/*.py`, and also includes `helm/values.yaml`, but the validator fails. Below is the details of the failure:

> ❌ Validator: DEPENDENT
> ❌ A dags file changed, you must push up the new image and then paste the image digest into the helm/values.yaml file.
> Input : archived_dags/tests/test_api_currencypay_assessments_extract.py,archived_dags/tests/test_api_currencypay_entries_extract.py,archived_dags/tests/test_api_currencypay_entriesorigins_extract.py,archived_dags/tests/test_api_currencypay_extract.py,archived_dags/tests/test_api_sf_extract.py,archived_dags/tests/test_api_sf_ods.py,archived_dags/tests/test_mssql_apollo_extract.py,archived_dags/tests/test_mssql_apollo_ods.py,archived_dags/tests/test_report_impressintofund_extract.py,archived_dags/tests/test_utility_currencypay_ods_refresh.py,archived_dags/tests/test_utility_ml_dags_start.py,archived_dags/tests/test_utility_sift_upload_test_data.py,dags/tests/test_api_currencypay_assessments_extract_v2.py,dags/tests/test_api_currencypay_disbursemententries_extract.py,dags/tests/test_api_currencypay_entries_extract_v2.py,dags/tests/test_api_currencypay_entryorigins_extract.py,dags/tests/test_api_currencypay_extract_v2.py,dags/tests/test_api_currencypay_ods.py,dags/tests/test_api_currencypay_reruns.py,dags/tests/test_api_currencypay_sessions_extract.py,dags/tests/test_api_currencypay_txnreports_extract.py,dags/tests/test_api_currencypay_txnresults_extract.py,dags/tests/test_api_currencypay_txns_extract.py,dags/tests/test_api_ga_extract.py,dags/tests/test_api_ga_ods.py,dags/tests/test_api_sf_extract_v2.py,dags/tests/test_api_sf_ods_v2.py,dags/tests/test_api_sf_reportdim.py,dags/tests/test_aws_ses_email_etl.py,dags/tests/test_composite_loan_load.py
> Settings : {"do":"dependent","changed":{"file":"dags/**/*.py","files":["helm/values.yaml"]},"message":"A dags file changed, you must push up the new image and then paste the image digest into the helm/values.yaml file."}

As you can see by doing a find on `.py` in the above text, the "Input" is only showing 30 files out of the 81 python files in the PR. I am thinking it is not just a display limitation but actually a programmatic limitation somewhere, because the validator should not have failed.

P.S. Sorry the PR is on a private repo so I can't link to it.

**Comment by shine2lay** [comment]
@alexbegg Whoa :open_mouth: , i don't think I've tested with that many inputs, thanks for bringing it up. I'll try to debug it, i suspect it could be because of pagination issues.

**Comment by alexbegg** [comment]
I played around with minimatch before and thought it might be where the issue is and I am right. I just debugged minimatch in node.js and realized it is acting weird, and it might be because I have some files in a `archived_dags` directory and some files in a `dags` directory, and the pattern is `dags/**/*.py`

So it doesn't seem to be a number of files issue at all.

With both a file in `archived_dags\` and a file in `dags\` and with the pattern of **`dags/**/*.py`** it is **false** 
```
minimatch('archived_dags/tests/test_utility_sift_upload_test_data.py,dags/tests/test_api_currencypay_assessments_extract_v2.py', 'dags/**/*.py')
```
With both a file in `archived_dags\` and a file in `dags\` and with the pattern of **`archived_dags/**/*.py`** it is **true**
```
minimatch('archived_dags/tests/test_utility_sift_upload_test_data.py,dags/tests/test_api_currencypay_assessments_extract_v2.py', 'archived_dags/**/*.py')
```

They should be true on both cases, right? Am I missing something? I guess I could use both patterns as a workaround, but it should have failed with `dags/**/*.py`

**Comment by shine2lay** [comment]
I don't think minimatch bug applies to mergeable because we compare individual file name against the pattern so the situation you describe seems like it wouldn't apply.

here is the line that checks if dependentFile is included

```
dependentFiles = modifiedFiles.some((filename) => minimatch(filename, validationSettings.changed.file))
```
[ref](https://github.com/mergeability/mergeable/blob/master/lib/validators/dependent.js#L62)

**Comment by alexbegg** [comment]
Yeah, it appears to be a minimatch bug and does not seem to be related to number of files, so I am closing this ticket

**Comment by shine2lay** [comment]
hmm.. good to know, thanks for debugging it @alexbegg

**Comment by alexbegg** [comment]
@shine2lay actually I am re-opening this because I didn't debug minimatch correctly and I believe it is as originally thought an issue of the input being limited to 30.

I forgot to do the `.some` and in there do the minimatch. I debugged using all 81 files and the dependent file being the last file, and the some function is returning **true**. So the list of files that GitHub returns I think must be limited in some way. Maybe it is a paginated endpoint? I think it is because the details on the checks page did not cut off any of the filenames but only had 30 files listed.

Here is my debugging results, first for 81 files, then with 30 files:

1. All 80 files...
```
dependentFiles: [ 'helm/values.yaml' ]
modifiedFiles: [
  'archived_dags/tests/test_api_currencypay_assessments_extract.py',
  'archived_dags/tests/test_api_currencypay_entries_extract.py',
  'archived_dags/tests/test_api_currencypay_entriesorigins_extract.py',
  'archived_dags/tests/test_api_currencypay_extract.py',
  'archived_dags/tests/test_api_sf_extract.py',
  'archived_dags/tests/test_api_sf_ods.py',
  'archived_dags/tests/test_mssql_apollo_extract.py',
  'archived_dags/tests/test_mssql_apollo_ods.py',
  'archived_dags/tests/test_report_impressintofund_extract.py',
  'archived_dags/tests/test_utility_currencypay_ods_refresh.py',
  'archived_dags/tests/test_utility_ml_dags_start.py',
  'archived_dags/tests/test_utility_sift_upload_test_data.py',
  'dags/tests/test_api_currencypay_assessments_extract_v2.py',
  'dags/tests/test_api_currencypay_disbursemententries_extract.py',
  'dags/tests/test_api_currencypay_entries_extract_v2.py',
  'dags/tests/test_api_currencypay_entryorigins_extract.py',
  'dags/tests/test_api_currencypay_extract_v2.py',
  'dags/tests/test_api_currencypay_ods.py',
  'dags/tests/test_api_currencypay_reruns.py',
  'dags/tests/test_api_currencypay_sessions_extract.py',
  'dags/tests/test_api_currencypay_txnreports_extract.py',
  'dags/tests/test_api_currencypay_txnresults_extract.py',
  'dags/tests/test_api_currencypay_txns_extract.py',
  'dags/tests/test_api_ga_extract.py',
  'dags/tests/test_api_ga_ods.py',
  'dags/tests/test_api_sf_extract_v2.py',
  'dags/tests/test_api_sf_ods_v2.py',
  'dags/tests/test_api_sf_reportdim.py',
  'dags/tests/test_aws_ses_email_etl.py',
  'dags/tests/test_composite_loan_load.py',
  'dags/tests/test_composite_sf_insert_cpho.py',
  'dags/tests/test_composite_sf_update_merchants.py',
  'dags/tests/test_composite_sf_upsert_collections.py',
  'dags/tests/test_composite_sf_upsert_tlo.py',
  'dags/tests/test_cosmosdb_abandonservice_extract.py',
  'dags/tests/test_cosmosdb_currencyanalysis_extract.py',
  'dags/tests/test_cosmosdb_currencyapi_extract.py',
  'dags/tests/test_cosmosdb_currencyfraud_extract.py',
  'dags/tests/test_cosmosdb_currencyinvoice_extract.py',
  'dags/tests/test_cosmosdb_currencylender_extract.py',
  'dags/tests/test_cosmosdb_currencynotification_extract.py',
  'dags/tests/test_cosmosdb_currencyrates_extract.py',
  'dags/tests/test_cosmosdb_currencyrates_ods.py',
  'dags/tests/test_cosmosdb_currencyreporting_extract.py',
  'dags/tests/test_cosmosdb_currencysales_extract.py',
  'dags/tests/test_cosmosdb_currencysales_ods.py',
  'dags/tests/test_cosmosdb_currencysalesforce_extract.py',
  'dags/tests/test_cosmosdb_currencysalesforce_ods.py',
  'dags/tests/test_cosmosdb_currencysql_extract.py',
  'dags/tests/test_cosmosdb_currencystips_extract.py',
  'dags/tests/test_cosmosdb_currencyvendor_extract.py',
  'dags/tests/test_cosmosdb_currencyvendor_ods.py',
  'dags/tests/test_mssql_apollo_extract_v2.py',
  'dags/tests/test_mssql_apollo_ods_v2.py',
  'dags/tests/test_mssql_creditbureau_extract.py',
  'dags/tests/test_ods_doosan_load.py',
  'dags/tests/test_report_cpay_new_merchant.py',
  'dags/tests/test_report_cpay_transaction_details_extract.py',
  'dags/tests/test_report_funnel_metrics_extract.py',
  'dags/tests/test_report_stage_comparison.py',
  'dags/tests/test_report_suntrust_mtd_opps.py',
  'dags/tests/test_report_suntrust_payment_approval.py',
  'dags/tests/test_scraper_currencypay2_load.py',
  'dags/tests/test_scraper_leaseworks_acglinfodwn_ods.py',
  'dags/tests/test_scraper_leaseworks_dm.py',
  'dags/tests/test_scraper_leaseworks_extract.py',
  'dags/tests/test_scraper_leaseworks_ods.py',
  'dags/tests/test_scraper_wasserstrom_load.py',
  'dags/tests/test_slack_app_summary.py',
  'dags/tests/test_utility_airflow_logs_cleanup.py',
  'dags/tests/test_utility_class_masking.py',
  'dags/tests/test_utility_currencypay_backfill_object.py',
  'dags/tests/test_utility_currencysalesforce_sync.py',
  'dags/tests/test_utility_deploy_airflow.py',
  'dags/tests/test_utility_remove_test_records.py',
  'dags/tests/test_utility_sf_backfill_fields.py',
  'dags/tests/test_utility_sf_backfill_object.py',
  'dags/tests/test_utility_sf_sync_deleted_recs.py',
  'dags/tests/test_utility_vendor_collection_update.py',
  'scripts/pytest_utils/pytest_template.py',
  'helm/values.yaml'
]
modifiedFiles.length: 81
_.difference(dependentFiles, modifiedFiles): []
isMergeable (fileDiff.length === 0): true
```
2. Now limited to 30...
```
dependentFiles: [ 'helm/values.yaml' ]
partialModifiedFiles: [
  'archived_dags/tests/test_api_currencypay_assessments_extract.py',
  'archived_dags/tests/test_api_currencypay_entries_extract.py',
  'archived_dags/tests/test_api_currencypay_entriesorigins_extract.py',
  'archived_dags/tests/test_api_currencypay_extract.py',
  'archived_dags/tests/test_api_sf_extract.py',
  'archived_dags/tests/test_api_sf_ods.py',
  'archived_dags/tests/test_mssql_apollo_extract.py',
  'archived_dags/tests/test_mssql_apollo_ods.py',
  'archived_dags/tests/test_report_impressintofund_extract.py',
  'archived_dags/tests/test_utility_currencypay_ods_refresh.py',
  'archived_dags/tests/test_utility_ml_dags_start.py',
  'archived_dags/tests/test_utility_sift_upload_test_data.py',
  'dags/tests/test_api_currencypay_assessments_extract_v2.py',
  'dags/tests/test_api_currencypay_disbursemententries_extract.py',
  'dags/tests/test_api_currencypay_entries_extract_v2.py',
  'dags/tests/test_api_currencypay_entryorigins_extract.py',
  'dags/tests/test_api_currencypay_extract_v2.py',
  'dags/tests/test_api_currencypay_ods.py',
  'dags/tests/test_api_currencypay_reruns.py',
  'dags/tests/test_api_currencypay_sessions_extract.py',
  'dags/tests/test_api_currencypay_txnreports_extract.py',
  'dags/tests/test_api_currencypay_txnresults_extract.py',
  'dags/tests/test_api_currencypay_txns_extract.py',
  'dags/tests/test_api_ga_extract.py',
  'dags/tests/test_api_ga_ods.py',
  'dags/tests/test_api_sf_extract_v2.py',
  'dags/tests/test_api_sf_ods_v2.py',
  'dags/tests/test_api_sf_reportdim.py',
  'dags/tests/test_aws_ses_email_etl.py',
  'dags/tests/test_composite_loan_load.py'
]
partialModifiedFiles.length: 30
_.difference(dependentFiles, partialModifiedFiles): [ 'helm/values.yaml' ]
isMergeable (fileDiff.length === 0): false
```

**Comment by shine2lay** [comment]
@alexbegg thanks for the debug info, i'll try to recreate the scenario and debug it.
