### ISSUE TITLE
How to get detected number of detected changes?

### ISSUE THREAD

**Issue by Nonnus** [mergeability/mergeable#366]
From the instructions, if we set a limit of 500, we are recommended to setup the feedback message as:
"your code has more than 500 changed files" which is not very useful
Is there any way to report the exact amount of changed files?
Thanks in advance

**Comment by shine2lay** [comment]
@Nonnus I don't think i fully understand the question, which validator are you referring to? 

Could you tell us a bit more about the use case you are trying to achieve? it may help us understand how we can best help you


> if we set a limit of 500, we are recommended to setup the feedback message as:
"your code has more than 500 changed files" which is not very useful

If the custom message is what you wish, you are free to specify the message you want.


> Is there any way to report the exact amount of changed files?

Are you asking if you can use the number of changed files found in a PR? I am very confused by this question.

**Comment by Nonnus** [comment]
Thanks a lot for your quick feedback @shine2lay 

```
> Is there any way to report the exact amount of changed files?
Are you asking if you can use the number of changed files found in a PR? I am very confused by this question.
```

Yes, that is exactly what we are asking 

Mainly we want to see if it is possible for Mergeable to report the exact number of changes it detects
The suggested report message is just a static hardcoded message and we would like to know if there is any variable we can use to get the amount of changes done.

Currently if one of our engineers has a pr failing mergeable, they have no idea to know if they are over the limit by a little bit or by a lot, even after editing the ignored files on configuration file we dont know how the changes affect the mergeable results.
Being able to report the detected changes would really help a lot in this regard

I hope I was able to make it a bit more clear now :)
Sorry if my initial post was confusing in any way

**Comment by shine2lay** [comment]
@Nonnus would you mind providing us with your current mergeable config? If the repo where the config is public and you don't mind, could you post a link to the repo as well?

**Comment by shine2lay** [comment]
@Nonnus try this
``` 
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: changeset
        max:
          count: 3
    fail:
      - do: checks # default fail case
        status: 'failure' # Can be: success, failure, neutral, cancelled, timed_out, or action_required
        payload:
          title: 'Mergeable Run have been Completed!'
          summary: |
            ### Status: {{toUpperCase validationStatus}}
                 Here are some stats of the run:
                 {{validationCount}} validations were ran.
                 {{passCount}} PASSED
                 {{failCount}} FAILED
          text: "
            {{#each validationSuites}}\n
                #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
                {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                       Input : {{{details.input.length}}}\n
                       Settings : {{{displaySettings details.settings}}}\n
               {{/each}}\n
            {{/each}}"
```

**Comment by Nonnus** [comment]
will do!
thanks a lot @shine2lay
