### ISSUE TITLE
merge action: add check for required status before attempting to merge

### ISSUE THREAD

**Issue by shine2lay** [mergeability/mergeable#386]
We are not checking required statuses currently before merging, as a result, when a new commit is pushed to PR and other required status (e.g circle ci) not finished, it'll throw error

**Comment by samj1912** [comment]
Fixed in #400. We can close this now.

**Comment by samj1912** [comment]
@shine2lay @jusx can we close this please?

**Comment by jusx** [comment]
fixed in #400
