### ISSUE TITLE
feature request: add validator for changes_requested

### ISSUE THREAD

**Issue by abid-mujtaba** [mergeability/mergeable#398]
Would be useful to trigger actions when a reviewer requests changes on a PR.

**Comment by samj1912** [comment]
This is already supported. You can validate and perform actions based on specific events. So you can make that event be pull_request.review_requested instead of `pull_request.*` See https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#pull_request for supported events.

**Comment by abid-mujtaba** [comment]
Interesting. Do you know if `pull_request_review.submitted` is triggered for just changes requested or for all three possibilities: comment, changes requested, and approved?

**Comment by abid-mujtaba** [comment]
The actual state of the `pull_request_review.submitted` event is in the `request.state` property of the payload ([docs](https://developer.github.com/webhooks/event-payloads/#pull_request_review)). It would be useful to have a validator that one can use to target the three possibilities: commented, changes requested, and approved.

Use case: I want to add a label to the PR when changes have been requested. 1 day after the label has been added I will start bugging the author by adding comments.

**Comment by abid-mujtaba** [comment]
A generic approach that would address this and also give users a lot of flexibility would be `EventPayload` validator which would match against the event payload. For example:

``` yaml
- when: pull_request_review.submitted
  - validate:
      - do: EventPayload
        match:
          request:
            state: commented
```

**Comment by jusx** [comment]
@abid-mujtaba That can certainly be very powerful and will cover a lot of cases. Food for thought.
