### ISSUE TITLE
Size validator: ignores hidden files by default

### ISSUE THREAD

**Issue by abid-mujtaba** [mergeability/mergeable#401]
The Size validator uses `minimatch` with its default config ([link](https://github.com/mergeability/mergeable/blob/2338bde456a76f8d41e90b8706fcf84d7f7d25dc/lib/validators/size.js#L271)) which ignores hidden files by default. Since that includes `.github/mergeable.yml`, this led me on a merry chase for several hours.

I believe that the Size validator should validate against **all** files in PR by default, including hidden files. The user can use `match` and `ignore` to modify this default behavior. This can be resolved easily by using the `dot` configuration in `minimatch`: [doc](https://github.com/isaacs/minimatch#dot).

**Comment by samj1912** [comment]
Interesting - I did not know that minimatch excluded hidden files. Does `**` not match all files?

**Comment by abid-mujtaba** [comment]
Not according to the [docs](https://github.com/isaacs/minimatch#dot):

> Note that by default, a/**/b will not match a/.d/b, unless dot is set.

**Comment by samj1912** [comment]
Fixed in #405
