### ISSUE TITLE
feature request: add null validator

### ISSUE THREAD

**Issue by abid-mujtaba** [mergeability/mergeable#402]
This arose from a discussion on #397. In certain use cases one wants to take an action on a specific event without any further validation (the event itself should trigger the event). For example, do something when a PR review is requested (triggered by `pull_request.review_requested`).

Currently all stanzas require a `validate` section. A solution is to introduce a **null** validator that does no actual validation, always passes, and so always triggers the relevant action.

**Comment by abid-mujtaba** [comment]
Attention: @samj1912

**Comment by jusx** [comment]
My original thought on this is to lean towards allowing for an empty validate section. IMO it makes more sense from a user experience perspective.

Thoughts?

**Comment by samj1912** [comment]
Yup, either works. I think a blank validate section makes sense. I also needed it recently for #396 actually.
