### ISSUE TITLE
label validator: does not support `pull_request.review_requested` or `pull_request.closed`

### ISSUE THREAD

**Issue by abid-mujtaba** [mergeability/mergeable#403]
Even though the [docs](https://mergeable.readthedocs.io/en/latest/validators/label.html) state that the Label validator supports `pull-request.*` the innards reveal that it does not (source: https://github.com/mergeability/mergeable/blob/master/lib/validators/label.js#L6).

This might be resulting in a `TypeError` I have been seeing:

> ❌ Error Occurred while executing an Action
If you believe this is an unexpected error, please report it on our issue tracker: https://github.com/mergeability/mergeable/issues/new
>
> Error Details
TypeError: Cannot read property 'schedule' of undefined

Is there a reason why the label validator should not be used with `pull_request.closed` or `pull_request.request_review`?

**Comment by samj1912** [comment]
@abid-mujtaba fixed with https://github.com/mergeability/mergeable/pull/404

I also added an example of a null validator.

**Comment by abid-mujtaba** [comment]
Awesome. Thanks @samj1912.
