### ISSUE TITLE
Mergeable reads config from pull requests making it unsafe

### ISSUE THREAD

**Issue by samj1912** [mergeability/mergeable#406]
Mergeable currently has merge access to repositories. Someone could potentially update the mergeable config for a repo and force merge PRs without maintianers knowing. This is because mergeable reads the config from PRs. We should introduce a flag to disable this behavior.

**Comment by jusx** [comment]
@samj1912 What do you have in mind in regards to syntax?

**Comment by samj1912** [comment]
I was thinking something simple - where if the PR is made from a fork - we should not read the config from the PR and if it is made from a branch originating from the same repo (at least that insures that the author has write access to the repo) we can read from it. It is the same principle by which Jenkins operates.

**Comment by jusx** [comment]
I like this, and I think that it makes a lot of sense.
