### ISSUE TITLE
feature request: add a validator for number of reviewers requested

### ISSUE THREAD

**Issue by abid-mujtaba** [mergeability/mergeable#410]
Use case: 

- An author creates a PR but does not add a reviewer.
- A domain-owner or assignee who is supposed to triage the PR fails to add a reviewer as well.

I want to be able to add a label (reviewer-needed) to the PR when the number of reviewers equals 0. This will be analogous to the `Assignee` validator. A lot of teams simply equate the author to the assignee and do care more about the reviewers.

Once 1 or 2 days have passed since the label was added I will start bugging the author/domain-owner/assignee by adding comments to the PR.

**Comment by samj1912** [comment]
Any reason for manually doing this instead of assigning a reviewer via an action?

**Comment by samj1912** [comment]
Also - duplicate of https://github.com/mergeability/mergeable/issues/393 ?

**Comment by abid-mujtaba** [comment]
Oops. Definitely a duplicate.

In our workflow we have a large number of possible reviewers and we don't want to assign someone automatically. A comment and/or a label when no reviewer has been requested for N days will remind observers.
