### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by artarazavi** [mergeability/mergeable#422]
I got this error not sure where to go from here:
HttpError: Resource not accessible by integration
    at /app/node_modules/@octokit/request/dist-node/index.js:66:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

it occured when I tried to do
- do: project
  must_include:
     regex: 'type|chore|wont'
     message: 'Custom message...'

**Comment by shine2lay** [comment]
@artarazavi this error occurs because mergeable doesn't have `read` permission on project. either explicitly give read permission or i think reinstalling mergeable should work (haven't tested it yet)

**Comment by jusx** [comment]
@artarazavi Are you running your own instance or using the Mergeable GH App?

**Comment by artarazavi** [comment]
@shine2lay I had to fix permissions and reinstall and it started to work thank you for your help!

**Comment by shine2lay** [comment]
glad that fixed it, i'll go ahead and close the issue then
