### ISSUE TITLE
Using Mergeable

### ISSUE THREAD

**Issue by nekuic** [mergeability/mergeable#423]
I try to use your application and have faced couple of problems.
1) Problem with config.I use next config:
```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
      - do: label
      must_exclude:
       regex: 'dont-merge'
       regex_flag: 'none' # Optional. Specify the flag for Regex. default is 'i', to disable default use 'none'
       message: 'Resticted'
```

And after I create pull request, mergeable fall with an error:
> Github API Error occurred while fetching the config file at .github/mergeable.yml
> Error from api: YAMLException: bad indentation of a mapping entry at line 6, column 7:
> must_exclude:

Example of the config I get in this article https://mergeable.readthedocs.io/en/latest/validators/label.html.

Could you tell, why I get this error? 

2) Mergeable execution.How it executes only when I create a pull request. Is it possible to execute Mergeable every time the branch of PR has been updated?

**Comment by shine2lay** [comment]
@nekuic 
1. I think when you copy-pasted, the editor didn't respect the proper indentations. `must_exclude` must line up with `do` and the stuff underneath must be one tab away from `must_exclude`
2. when you define `when: pull_request.*` that means, mergeable will execute when any of the `pull_request` event triggers, see all events here https://developer.github.com/webhooks/event-payloads/#pull_request

**Comment by nekuic** [comment]
@shine2lay 
I look at example at here https://github.com/mergeability/mergeable/blob/master/.github/mergeable.yml and make the next one config:
`
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: label
          must_exclude:
            regex: 'dont-merge'
            message: 'Resticted'
`
After creation of PR I get an error:

> Github API Error occurred while fetching the config file at .github/mergeable.yml
> Error from api: YAMLException: bad indentation of a mapping entry at line 7, column 11:
> must_exclude:

When I make a '-" before must_exclude option I get an error:

> Github API Error occurred while fetching the config file at .github/mergeable.yml
> Error from api: YAMLException: bad indentation of a mapping entry at line 7, column 11:
> - must_exclude:

**Comment by jusx** [comment]
@nekuic the `must_exclude` option is at the same indentation level as the `do`. Like so:

```yml
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: label
         must_exclude:
            regex: 'dont-merge'
            message: 'Resticted'
```

**Comment by nekuic** [comment]
@jusx I copy-paste your example and get an error:

> Github API Error occurred while fetching the config file at .github/mergeable.yml
> Error from api: YAMLException: bad indentation of a mapping entry at line 6, column 22:
> must_exclude:

I give you an access to my repo (nekuic/kno_test) where you can see an error.

**Comment by jusx** [comment]
@nekuic If you don't mind, please make the repo public if you wish for me to take a look. 

The error message is specifically pointing out that line 6 indentation is bad. It is a standard YML formatting error. Please make sure to format your YML appropriately.

We use [js-yaml](https://github.com/nodeca/js-yaml) to load the config and the error is coming straight from it. For convenience, I suggest you load your YML with your config on localhost to verify that you have the formatting right.
