### ISSUE TITLE
Approvals don't trigger a refresh

### ISSUE THREAD

**Issue by artarazavi** [mergeability/mergeable#426]
I was doing some testing and I realized that when you edit the title or description of a PR it triggers a Mergeable re-fresh. The same does not happen for approvals. If someone approves the PR you have to click on mergeable details and hard refresh from there. That is the only way you can get mergeable to pass for an approver.

**Comment by shine2lay** [comment]
@artarazavi Do you by chance have `pull_request_review.*` in your `when` ? the approval is a part of the pull_request_review event class IIRC. 

https://developer.github.com/webhooks/event-payloads/#pull_request_review

**Comment by artarazavi** [comment]
@shine2lay that fixed my problem thank you so much!

**Comment by shine2lay** [comment]
cool, i'll close this issue then
