### ISSUE TITLE
Is it possible request review for a GitHub Team?

### ISSUE THREAD

**Issue by joasgarcia** [mergeability/mergeable#430]
Using [reviewers field](https://mergeable.readthedocs.io/en/latest/actions/request_review.html), for example: 
```yaml
- do: request_review
        reviewers: ['org/team-slug']
```

**Comment by shine2lay** [comment]
@joasgarcia to my knowledge, no. we don't have that feature yet. It'll be a cool feature tho.

**Comment by bbugh** [comment]
@joasgarcia I created a PR for this in #574 if you want to try it out.
