### ISSUE TITLE
About greet new contributor recipe

### ISSUE THREAD

**Issue by joasgarcia** [mergeability/mergeable#432]
If I use exactly this recipe: https://mergeable.readthedocs.io/en/latest/recipes.html#greet-a-new-contributor the comment will be posted only in the first contributor PR or in every new PR?

**Comment by shine2lay** [comment]
@joasgarcia this will create a comment for every new PR

**Comment by shine2lay** [comment]
please re-open if you are requesting a feature where it will only show comment for first time contributors. i am closing the issue for now
