### ISSUE TITLE
Better logs for failures in PR home page without going to details

### ISSUE THREAD

**Issue by iammuho** [mergeability/mergeable#446]
On the PR home page, we can improve the logs for failures by writing how many failures and names of validations.

Sample:
<img width="884" alt="Screenshot 2020-12-18 at 11 05 51" src="https://user-images.githubusercontent.com/1788968/102605663-e4041400-4125-11eb-8e42-529684269726.png">

**Comment by jusx** [comment]
Fixed by #447
