### ISSUE TITLE
Github actions support rather than CircleCI

### ISSUE THREAD

**Issue by iammuho** [mergeability/mergeable#450]
Github actions are free for public repositories and for fork projects (also here), it's easier to install like testing and docker release rather than CircleCI which needs to be registered, deployed etc.

**Comment by jusx** [comment]
@iammuho @diegomarangoni We now have two workflows for pushing to dockerhub: `docker` and `release` 

I'd like to combine the two, keeping the use of `secret. DOCKERHUB_REPO` and pushing when the branch is tagged.

Was there a specific reason for the two separate workflows?

**Comment by jusx** [comment]
I'm aware the docker workflows aren't working. The conditional `if` does not work with secrets. I'll push up a fix soon.

**Comment by diegomarangoni** [comment]
hey @jusx, there was no specific reason for having both workflows, I think we did some mistake here, sorry.
I see you removed, it's perfect now, thanks!

**Comment by jusx** [comment]
Awesome.
