### ISSUE TITLE
Is it possible to check when PR is opened on main branch?

### ISSUE THREAD

**Issue by baeharam** [mergeability/mergeable#457]
PR A (base: `main`) ---> needs two labels to be merged: `qa passed`, `develop deployed`.
PR B (base: `some-branch`) ---> could be merged anytime.

I know `BaseRef` option is implemented by #343 , but how can I implement above configuration? Is it impossible?

**Comment by shine2lay** [comment]
@baeharam so sorry for the late reply, i believe we can support your use case, please try this configuration

version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'check labels if in master base branch'
    validate:
      - do: or
        validate:
          - do: and
            validate:
              - do: baseRef
                must_include:
                  regex: 'main'
              - do: label
                and:
                  - must_include:
                      regex: 'qa passed'
                  - must_include:
                      regex: 'develop deployed'
          - do: baseRef
            must_exclude:
              regex: 'main'
```

**Comment by jusx** [comment]
@baeharam Closing this issue. Please feel free to re-open and comment if the above recipe is not working for you.

**Comment by baeharam** [comment]
@shine2lay @jusx Sorry for late response, it works great! Thanks.
