### ISSUE TITLE
Bug: unknown_error_validator --- HttpError not found

### ISSUE THREAD

**Issue by shine2lay** [mergeability/mergeable#488]
![image](https://user-images.githubusercontent.com/5243508/105284054-83258c80-5b66-11eb-9567-719b432af3a0.png)

this is occurring to multiple repos,
from a first glance, it could be `milestone` validator, will investigate more

Update: the error stems from deepvalidation component of the milestone validator

**Comment by jusx** [comment]
@shine2lay Looks like this only affects issues when using the milestone validator. Did this come up only after the probot upgrade of is it an older bug?
