### ISSUE TITLE
Support for probot scheduler

### ISSUE THREAD

**Issue by shine2lay** [mergeability/mergeable#499]
We've recently had to upgrade to the latest version of probot which probot-scheduler does not support. Furthermore https://github.com/probot/scheduler is no longer maintained. We have two options:

Deprecate the scheduler event.
Fork probot-scheduler and update it to work with the latest version of probot. This will incur maintenance cost.
Depending on what route we take, the scheduler events may no longer be relevant.

Would love to hear everyone's thoughts here. Is the scheduler event of value?  (Taken from this [comment](https://github.com/mergeability/mergeable/pull/496#issuecomment-771267951))

please check the comment to see current discussion.

**Comment by jusx** [comment]
> Makes sense. Would you want to fork it, or simply add it to mergeable? The actual scheduler code is fairly small and simple and it could easily fit in a PR. I think once it works with mergeable, then we can generalize it and make a standalone module that others can use.

@samj1912 Moving the conversation here. You are right that the `probot-scheduler` code base is small. Looking at the code, I think we can keep it fairly generic as is even when it's within the mergeable code base. I think we should extract it soon after.
