### ISSUE TITLE
Central Cache

### ISSUE THREAD

**Issue by iammuho** [mergeability/mergeable#502]
**Problem:**

Today we have encountered a problem with the configuration cache. There is a method called `resetCache` which clears the cache if PR has `mergeable.yml` but the problem is it clears in `memory` so `pod` level (for k8s users) but when you have more than 1 pods, some pods are fresh and some of them are being out-of-sync.

**Solution:**

To solve this problem, we need to create a feature to enable REDIS to support central cache.

**Comment by samj1912** [comment]
Yeah, I had a similar issue. I fixed it by simply adding a small ttl of 30 seconds. Helps with bursty events and still works as intended.

**Comment by shine2lay** [comment]
implemented in #506
