### ISSUE TITLE
Details link should go to the checks report

### ISSUE THREAD

**Issue by laughedelic** [mergeability/mergeable#520]
Right now whenever a Mergeable check fails and I want to click on `Details` link, it goes to `https://github.com/jusx/mergeable`, so I have to manually open the Checks tab and navigate to the Mergeable run. It would be much more convenient if the details link pointed to that check run page.

**Comment by shine2lay** [comment]
hey @laughedelic, I am not sure I follow, which "details" link are you referring to?

**Comment by laughedelic** [comment]
@shine2lay sorry for not including a screenshot. I mean the link on the **right side** of the PR check status:
<img width="831" alt="Screenshot 2021-03-04 at 18 31 02" src="https://user-images.githubusercontent.com/766656/110004494-cb180180-7d17-11eb-9596-e0f5bcf3d508.png">

**Comment by laughedelic** [comment]
It's worth noting that _sometimes_ the link points to the check run page like 
```
https://github.com/org/repo/pull/123/checks?check_run_id=2033303925
```

I just saw that on a _successful_ check. But that link is most needed when it fails to see the details, not when it succeeds.

**Comment by shine2lay** [comment]
@laughedelic Can you possibly share the repo where this is occurring? That shouldn't happen (i haven't seen it happen either) and I also think we don't have control over that.

**Comment by laughedelic** [comment]
@shine2lay unfortunately I can't share the repositories where I observe this issue, they are private. Could it be a problem only in private repositories?

**Comment by laughedelic** [comment]
Actually, I can see it in this same repository: https://github.com/mergeability/mergeable/pull/519, if you scroll down and look at the failed Mergeable check, its Details link points to `https://github.com/jusx/mergeable`.

**Comment by laughedelic** [comment]
<img width="621" alt="Screenshot 2021-03-04 at 20 20 01" src="https://user-images.githubusercontent.com/766656/110017895-0110b200-7d27-11eb-9904-c83d14ccef7f.png">

Pointer is on the Details link on the right, and in the left corner you can see where it points

**Comment by shine2lay** [comment]
@laughedelic that is weird, that doesn't happen for me at all, in fact I tested it on the same PR before I replied to your comment. 
I've attached a screen shot
![image](https://user-images.githubusercontent.com/5243508/110018886-a3577800-7cdc-11eb-8a80-ea31f40e0e73.png)

**Comment by laughedelic** [comment]
Okay, thanks for verifying. Then it has to be one of the many Chrome extensions I have. I tried opening it in incognito mode without extensions and saw the correct link. I'll try to narrow it down and report back.

**Comment by laughedelic** [comment]
And the culprit seems to be the GitHub Refined extension, the most useful one 😞

**Comment by laughedelic** [comment]
- https://github.com/sindresorhus/refined-github/issues/3938
- https://github.com/sindresorhus/refined-github/issues/4015

**Comment by shine2lay** [comment]
Thanks for finding the problem, I am going to close the issue since there is nothing we can do on our side unless we have a web interface, which I don't think will happen anytime soon.

**Comment by laughedelic** [comment]
Sure. Thanks for helping me to identify the problem.
