### ISSUE TITLE
Release & publish docker images with versioning after release is completed

### ISSUE THREAD

**Issue by quike** [mergeability/mergeable#597]
We are coming from https://github.com/mergeability/mergeable/issues/554

The purpose of the issue would be to build and publish a new docker  mergeable image with the new version after the release is completed.
Currently the docker job is ignored and no new builds are published. The idea is to connect both workflows so one follows another one and new artifacts can be deployed to be consumed with the right version.

Besides current Dockerfile is off in comparison of nodejs version used by the app 

Dockerfile: `FROM node:12.16.0`
package.json: `14.15.4`

@shine2lay any reason why docker images are not built? github rate limitations?

**Comment by shine2lay** [comment]
@quike i am not aware of a blocker to build docker images, we just haven't gotten around to it.

**Comment by boekkooi-lengoo** [comment]
@shine2lay are you planning to enable pushing to https://hub.docker.com/r/mergeability/mergeable?
It would be great to have an official build. 
Based on [.github/workflows/docker.yml](https://github.com/mergeability/mergeable/blob/master/.github/workflows/docker.yml) it looks like [adding the secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository) `DOCKERHUB_PUSH`, `DOCKERHUB_USERNAME`, `DOCKERHUB_PASSWORD` and `DOCKERHUB_REPO` would enable this.

**Comment by tenshiAMD** [comment]
@boekkooi-lengoo looks like it is purposely disabled by them

**Comment by Ch4s3r** [comment]
The issue linked in the `docker.yml` regarding the [workaround](https://github.community/t5/GitHub-Actions/jobs-lt-job-id-gt-if-does-not-work-with-env-secrets/m-p/38549) does not exist anymore.
Is there a possibility to enable the publishing of docker images again?
