### ISSUE TITLE
When open a PR "Mergeable — No Config file found" error occurs

### ISSUE THREAD

**Issue by munkherdeneen** [mergeability/mergeable#652]
Currently, I am facing 3 different issues on my Merge bot which is hosted on-prem.

1. When I open up a new PR from the main branch it always gives the following error even though both main and branches have "./github/mergeable.yml" in the repo.

"Mergeable — No Config file found"

![image](https://user-images.githubusercontent.com/55971205/186031993-ed5f4997-b0da-4873-a480-46531bd05a19.png)

The local hosted merge bot writes the following log when PR open action happened.
![image](https://user-images.githubusercontent.com/55971205/186267618-d7d8e4c5-f37c-4549-a1de-8163e63da978.png)

Then when I change the edit "./github/mergeable.yml" file add white space in the branch then it pickups up the config file and runs fine.

![image](https://user-images.githubusercontent.com/55971205/186032334-3694a517-8f1d-4846-b75a-eaf369eb9666.png)

Could you support on this issue that how to tackle this issue?

2. How can you run the scheduler on on-prem machines? Even when I enable the scheduler with the following variables it does not run for us. In this case, how can we make it run?

![image](https://user-images.githubusercontent.com/55971205/186032906-700cbbd4-7337-4658-a16f-4bf65596a5ea.png)

Even it starts with scheduler mode:

![image](https://user-images.githubusercontent.com/55971205/186033263-dbfddaf3-c799-431f-b427-c37b1bb37e04.png)

3. When I start the server it gives the following error and keeps writing it every minute what could be the potential cause of it?

![image](https://user-images.githubusercontent.com/55971205/186033417-317c775f-c226-4b2d-a437-a609280dd484.png)

Thank you 😉.

**Comment by shine2lay** [comment]
@munkherdeneen 
re 1: interesting, IIRC, if we detect `invalid-yaml` I thought we created a failed check saying `invalid-yaml`. I'll have to look deeper to understand where this could've went wrong. 
re 2 & 3: It sounds like an connection error, I have never encountered it, maybe try to make sure you can ping the server?

**Comment by munkherdeneen** [comment]
I am closing this issue since I sorted out my main issue which is #1.
