### ISSUE TITLE
Support regex matching in `begins_with` and `ends_with`

### ISSUE THREAD

**Issue by tenshiAMD** [mergeability/mergeable#658]
I just noticed that `begins_with` and `ends_with` does not use regex matcher at all. This can be an enhancement in the future.

**Comment by tenshiAMD** [comment]
@shine2lay what do you think?

**Comment by tenshiAMD** [comment]
@shine2lay ok I see if that's the case, I suggest adding in the documentation referring to `must_include` so the user will have a better understanding. For me, `begins_with` is more likely to have regex matching than `must_include`. 

> Can you think of case(s) where must_include doesn't cover?

I will inform you if I have in mind. Thanks!

**Comment by tenshiAMD** [comment]
@shine2lay or what do you think of depreciating `begins_with` and `ends_with`? in favor of `must_include` then adding some examples of its use cases the same as the two options.

**Comment by shine2lay** [comment]
@tenshiAMD I made the same argument when we first implemented it, @jusx particular wanted to have it. He wanted non-regex users to use it easily too IIRC.

**Comment by shine2lay** [comment]
> @shine2lay ok I see if that's the case, I suggest adding in the documentation referring to `must_include` so the user will have a better understanding. For me, `begins_with` is more likely to have regex matching than `must_include`.

We use "match" instead of "regex" for `begins_with` and `ends_with` for this reason

**Comment by tenshiAMD** [comment]
@shine2lay ok I see so we cannot use `begins_with` and `ends_with` at the same time with `must_include` then.

**Comment by tenshiAMD** [comment]
@shine2lay I guess we can add `match_exact` option for `must_include` or something else like it.

**Comment by shine2lay** [comment]
> @shine2lay ok I see so we cannot use `begins_with` and `ends_with` at the same time with `must_include` then, and vice versa.

No, you can use it, each validation is independent. 

> @shine2lay I guess we can add `match_start` and `match_end` option for `must_include` or something else like it to make the same behavior for `begins_with` and `ends_with` so we use both. What do you think?

`must_include` can already do everything generally, if users want to have different regexes to match against the same input, they can use `and` and `or`

**Comment by tenshiAMD** [comment]
@shine2lay I guess we can close this. Thanks for enlightening me!
