### ISSUE TITLE
New updates are not applying in live

### ISSUE THREAD

**Issue by tenshiAMD** [mergeability/mergeable#659]
I noticed that our new updates are not applying. Please check. Thanks!

**Comment by tenshiAMD** [comment]
@shine2lay hi, any updates? Thanks!

**Comment by tenshiAMD** [comment]
@shine2lay hi, any updates? Thanks!

**Comment by shine2lay** [comment]
@tenshiAMD I am blocked by @jusx , I already pinged him, I need him to unblock me before I try to solve it.

**Comment by tenshiAMD** [comment]
@shine2lay hi, any updates? Thanks!

CC @jusx 

> @tenshiAMD I am blocked by @jusx , I already pinged him, I need him to unblock me before I try to solve it.

**Comment by tenshiAMD** [comment]
@shine2lay great all works now https://github.com/mergeability/mergeable/issues/654#issuecomment-1234520841. Thanks! I'm closing this one
