### ISSUE TITLE
Mergeable has been not running for the last few days

### ISSUE THREAD

**Issue by dfawley** [mergeability/mergeable#746]
For the last few days, our PRs have been getting stuck on Mergeable with the status `Expected — Waiting for status to be reported`.  I'm not sure there's much else we can debug at this point.  Our config hasn't changed in 3 years, and I confirmed the app still has repo access.  I have been force merging all of our PRs in the meantime.

Example PR: https://github.com/grpc/grpc-go/pull/7214

Please let me know what we can do to help resolve this.  Thanks!

**Comment by michalakadam** [comment]
Our repo is also affected. Since it's a second issue this year, we've decided to migrate fully to https://github.com/palantir/policy-bot

**Comment by shine2lay** [comment]
@dfawley it seems last deploy had an issue... I've rolled back the latest deploy

**Comment by dfawley** [comment]
Thank you!  Things seem to be working again.  I'll leave this open in case you want to follow-up here.  Otherwise feel free to close.
